# Generated by Django 3.2.11 on 2022-01-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0002_auto_20220123_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'verbose_name': 'Fruta', 'verbose_name_plural': 'Frutas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Regiao', 'verbose_name_plural': 'Regioes'},
        ),
    ]
