# Generated by Django 3.2.11 on 2022-01-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0003_auto_20220123_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'verbose_name': 'Fruit', 'verbose_name_plural': 'Fruts'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='regiao',
        ),
        migrations.AddField(
            model_name='fruit',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='fruits_related', to='frexco.region'),
            preserve_default=False,
        ),
    ]
